language: rust
services: docker
rust:
- stable
- beta
- nightly
install:
  - cargo install cross
  - source ~/.cargo/env || true
script:
  - cross build --target $TARGET
  - cross build --target $TARGET --release
matrix:
  include:
    env:
      - TARGET=armv7-unknown-linux-gnueabihf
      - TARGET=armv7-unknown-linux-musleabihf
  allow_failures:
  - rust: nightly
