language: rust
cache: cargo
services: docker
rust:
  - stable
  - beta
  - nightly
install:
  - cargo install cross || true
  - source ~/.cargo/env || true
script:
  - cross build --target $TARGET
  - cross build --target $TARGET --release
env:
  - TARGET=armv7-unknown-linux-gnueabihf
  - TARGET=armv7-unknown-linux-musleabihf
  - TARGET=aarch64-unknown-linux-gnu
  - TARGET=aarch64-unknown-linux-musl
matrix:
  allow_failures:
    - rust: nightly
