[package]
name = "rppal"
version = "0.5.1"
authors = ["Rene van der Meer <rene@golemparts.com>"]
description = "Interface for the Raspberry Pi's GPIO and SPI peripherals."
documentation = "https://docs.golemparts.com/rppal"
repository = "https://github.com/golemparts/rppal"
readme = "README.md"
license = "MIT"
categories = ["embedded", "hardware-support"]
keywords = ["raspberry","pi","gpio","spi"]

[dependencies]
libc = "0.2"
quick-error = "1.1"
mio = "0.6"
mio-extras = "2.0"
