[package]
name = "rppal"
version = "0.10.0" # Also update html_root_url in lib.rs
edition = "2018"
authors = ["Rene van der Meer <rene@golemparts.com>"]
description = "Interface for the Raspberry Pi's GPIO, I2C, PWM and SPI peripherals."
documentation = "https://docs.golemparts.com/rppal"
repository = "https://github.com/golemparts/rppal"
readme = "README.md"
license = "MIT"
categories = ["embedded", "hardware-support"]
keywords = ["raspberry","pi","gpio","spi","i2c"]

[dependencies]
libc = "0.2"
lazy_static = "1.2"
nb = { version = "0.1", optional = true }
embedded-hal = { version = "0.2", optional = true }

[dev-dependencies]
simple-signal = "1.1"

[features]
default = []
hal = ["nb", "embedded-hal"]
