[package]
name = "rppal"
version = "0.5.0"
authors = ["Rene van der Meer <rene@golemparts.com>"]
description = "Interface for the Raspberry Pi GPIO through /dev/gpiomem or /dev/mem."
documentation = "https://docs.golemparts.com/rppal"
repository = "https://github.com/golemparts/rppal"
readme = "README.md"
license = "MIT"
categories = ["embedded", "hardware-support"]
keywords = ["raspberry","pi","gpio","peripherals"]

[dependencies]
libc = "0.2"
enum_primitive = "0.1"
quick-error = "1.1"
mio = "0.6"
mio-extras = "2.0"
users = "0.6"
fnv = "1.0"

[dependencies.num]
version = "0.1"
default-features = false
