[package]
name = "rppal"
version = "0.10.0" # Also update html_root_url in lib.rs
edition = "2018"
authors = ["Rene van der Meer <rene@golemparts.com>"]
description = "Interface for the Raspberry Pi's GPIO, I2C, PWM and SPI peripherals."
documentation = "https://docs.golemparts.com/rppal"
repository = "https://github.com/golemparts/rppal"
readme = "README.md"
license = "MIT"
categories = ["embedded", "hardware-support"]
keywords = ["raspberry","pi","gpio","spi","i2c"]

[dependencies]
libc = "0.2"
quick-error = "1.2"
